application: versionswitcher
version: 0001_0001
runtime: python
api_version: 1

handlers:
  - url: /css
    static_dir: static/css
  - url: /js
    static_dir: static/js
  - url: /img
    static_dir: static/img
  - url: /favicon.ico
    static_files: static/img/favicon.ico
    upload: static/img/favicon.ico
    mime_type: image/x-icon
    #mime_type: image/vnd.microsoft.icon
#  - url: /versionswitcher\.sh
#    static_files: static/scripts/versionswitcher.sh
#    upload: static/scripts/versionswitcher\.sh
#    mime_type: text/plain
  - url: /install\.sh
    static_files: static/scripts/install.sh
    upload: static/scripts/install\.sh
    mime_type: text/plain
#  - url: /bootstrap\.sh
#    static_files: static/scripts/bootstrap.sh
#    upload: static/scripts/bootstrap\.sh
#    mime_type: text/plain
  #- url: /static
  #  static_dir: static
  #- url: /versions
  #  static_dir: static/versions
  #- url: /scripts
  #  static_dir: static/scripts
  - url: /scripts/.*
    script: static_file.py
  - url: /data/.*
    script: static_file.py
  - url: /installers/.*
    script: static_file.py
  - url: /hooks/.*
    script: static_file.py
  - url: /misc/.*
    script: static_file.py
  - url: /archives
    static_dir: static/archives
    mime_type: text/plain
  - url: /versionwatcher
    script: koko.versionwatcher_handler.py
    login: admin
  - url: /.*
    script: index.py


skip_files: |
  ^(.*/)?(
  (app\.ya?ml)|
  (index\.ya?ml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (test/.*)|
  )$
